TEST : GITHUB action

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -11,19 +11,55 @@ on:
     branches: [ master ]
 
 jobs:
-
-
-  test:
-    name: Unit Test
+  deploy:
+    name: Deploy project
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v2
-      - name: Set up JDK 1.8
-        uses: actions/setup-java@v1
+      - name: Install SSH Key
+        uses: shimataro/ssh-key-action@v2
         with:
-          java-version: 1.8
-      - name: Maven Package
-        run: mvn -B clean package
-      - name: Maven Verify
-        run: mvn -B clean verify
-        
+          key: ${{ secrets.SSH_PRIVATE_KEY }}
+          known_hosts: 'hosts'
+      - name: Adding Know Hosts
+        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
+      - name: Deploy with rsync
+        run: |
+          ls -ail ./
+          rsync -avz ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/pi/
+
+
+
+        #  test:
+        #    name: Unit Test
+        #    runs-on: ubuntu-latest
+        #
+        #    services:
+        #      mariadb:
+        #        image: mariadb:latest
+        #        ports:
+        #          - 3306
+        #        env:
+        #          MYSQL_USER: admin
+        #          MYSQL_PASSWORD: admin
+        #          MYSQL_DATABASE: codev
+        #          MYSQL_ROOT_PASSWORD: admin
+        #          options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3
+        #
+        #    steps:
+        #      - uses: actions/checkout@v1
+        #      - name: Verify MariaDB connection
+        #        env:
+        #          PORT: ${{ job.services.mariadb.ports[3306] }}
+        #        run: |
+        #          while ! mysqladmin ping -h"127.0.0.1" -P"$PORT" --silent; do
+        #            sleep 1
+        #          done
+        #      - uses: actions/checkout@v2
+        #      - name: Set up JDK 1.8
+        #        uses: actions/setup-java@v1
+        #        with:
+        #          java-version: 1.8
+        #      - name: Maven Verify
+        #        run: mvn -B clean verify
+
+
